site_name: Jcan
site_url: https://9wang.github.io/test/
theme:
  name: 'material'
nav:
  - Home: index.md
  - User Guide:
      -'g1': about.md
      -'License': license.md
plugins:
  - serach
markdown_extensions:
  -toc:
     permalink: true